### PR TITLE
Merge 3.3/develop into 3.4/develop

### PR DESCRIPTION
**Pull request by enov**
Also
- Update minimum PHP version in test matrix

### CODE REVIEW

**Comment by enov** [comment]
Thanks @acoulton. Another thing I just noticed, is that PHPUnit 4.0.0 is used throughout the matrix.

**Comment by acoulton** [comment]
composer.json specifies v4 - looks like it came in your merge conflict resolution in fb5b07d407 

kohana/core still doesn't build with this merged - I was waiting to see if it needed packagist to update but I think maybe there's something in 3.4 that isn't compatible with phpunit4 mocking or something? Does it run for you locally?

**Comment by enov** [comment]
Yes, that came with the merge conflict resolution. I'll make another PR for that.

**Comment by enov** [comment]
@acoulton Please review and merge #52. I still believe things will get fixed after the merge.

I mistakenly used this semver checker http://jubianchi.github.io/semver-check/ and thought that specifying v4 would be enough.

Thanks.

**Comment by enov** [comment]
> Does it run for you locally?

I am working on a VM that has HHVM and it runs with both PHPUnit 4.7.6 and PHPUnit 4.0.0.

**Comment by acoulton** [comment]
OK I've merged #52 and kohana/core#639 - hopefully the branch builds will be green now.

**Comment by acoulton** [comment]
@enov hm, still looks like the build is broken with PHPUnit 4.0.0 on PHP 5.4

**Comment by enov** [comment]
Will look at this.

**Comment by enov** [comment]
@acoulton I am still looking at this. The build is not broken with PHPUnit 4.0.0 on PHP 5.4 because on this PR PHPUnit 4.0.0 is used throughout the matrix and it's green on the first PHP 5.4 (the first one, not the additional build with `composer update --prefer-lowest`).

**Comment by enov** [comment]
Finally, I was able to narrow down the issue. When using the following command:

```
composer update --prefer-lowest --with-dependencies phpunit/phpunit
```

Composer is installing the lowest possible version of the dependencies as well. A notable difference is with the package `phpunit-mock-objects` that has version `2.0.0` when installed with the above command. When PHPUnit `4.0.0` is required manually, that package has version `2.0.10`.

Now, allow me to suggest the following three solutions:
- #53: Force phpunit-mock-objects via composer.json to be at least `2.0.8`. This is the least version that makes the tests green again. However, this constraint needs additional work, as the `--prefer-lowest` command shown above installs PHPUnit `4.1.0`.
- #54: Just update the supported PHPUnit version to `^4.1`, which makes the tests green without additional headaches. Unfortunately, that defeats the purpose of #52.
- Another suggestion would be to `composer update --prefer-lowest phpunit/phpunit` without `--with-dependencies`. This installs PHPUnit version `4.6.0`

So, @acoulton, and anyone else, please comment on my findings. I am sorry if my last PRs were a bit lousy.

Thank you.

**Comment by enov** [comment]
I used PHPUnit 4.0 by manually doing `composer require PHPUnit 4.0`, and it's working fine.

However, if we want to use `--prefer-lowest`, then I personally lean towards the third solution I proposed above, to simply `composer update --prefer-lowest phpunit/phpunit` without `--with-dependencies`.

**Comment by acoulton** [comment]
@enov the point of adding this extra build was to make sure that kohana does actually build successfully with the lowest version of all dependencies that satisfy our constraints.

If the build doesn't pass with the lowest 4.\* version of phpunit without specifying other restrictions, then either we need to fix kohana so it does, or fix composer.json to specify the right minimum version. Dropping the `--with-dependencies` defeats the point of running this test at all.

Since this is 3.4 and we can make breaking changes, I would just update the minimum phpunit version - maybe even to `^4.8` - which should take care of everything? Why do we need to support any older version for this branch?

**Comment by enov** [comment]
The original idea was to test with the lowest version of PHPUnit we support. Why should we care for the lowest versions of its dependencies; we can not patch all the differences and bugs of all those packages into Kohana.

Also, if we want to build successfully with the lowest version of all dependencies that satisfy our constraints, then we should not run the composer update on phpunit/phpunit alone.

It might have been more useful if `--prefer-lowest` would only take care of the lowest of the immediate dependencies, and continue resolving dependencies with the standard policies.

In all cases, I agree we should do something about the minimum phpunit version. `^4.8` would be nice, but I am also a bit worried about leaving behind version 4.2 [as HHVM official frameworks test runs on it](https://github.com/facebook/hhvm/blob/master/hphp/test/frameworks/composer.json#L3).

**Comment by acoulton** [comment]
If we claim to support PHPUnit 4.0.0 (with no other constraints) but don't actually support some valid installations of that version then our composer.json is lying.

We shouldn't have to patch all the differences and bugs of earlier packages into Kohana, but we should specify a valid set of dependency constraints so that if a user tries to force composer to install phpunit-mock-objects@2.0.7 for whatever reason (including requiring another package that somehow depends on that earlier version) composer immediately tells them that it's not going to work.

It's also important so that it's safe for someone to update their own application by just running `composer update kohana/unittest` - so they get an immediate failure if their composer.lock is pinning an old version of phpunit-mock-objects.

That means we either specify a known-good phpunit/phpunit version overall (easier for us to maintain), or we add a specific constraint on the minor bugfix version of phpunit-mock-objects that we require (more flexible for end user).

You're right that really we should be testing `--prefer-lowest` on all dependencies - _but_ currently AFAIK the only external dependency is phpunit, and because of the way kohana is structured there are issues testing newer versions of one module with older versions of another? Though technically we should probably resolve that eg by tagging a koharness release and updating the composer.json requirement.

**Comment by enov** [comment]
Yes, I understand that PHPUnit should not be considered as a monolithic library but rather a set of packages that might be used within applications and those might lock for specific versions.

I will look deeper into `phpunit-mock-objects` to see why we have the error. Also, I will do some clean ups.

**Comment by enov** [comment]
Bingo! #53

**Pull request merged**
