### PR TITLE
Remove assertType compatability for older PHPUnit versions

### PR DESCRIPTION
**Pull request by enov**

### CODE REVIEW

**Comment by enov** [comment]
I can not find the commit related to this PR in `git log`:
- When I clone the repository and do a `git log`
- When I look at [the commits log here on Github](https://github.com/kohana/unittest/commits/3.3/develop)
- When I [compare branches](https://github.com/kohana/unittest/compare/3.4/develop...3.3/develop) with `3.4/develop` as base

At first, I thought there was a bug in Github interface and I contacted them. I still did not hear anything from them. Now, it does not look like a bug in the Github interface anymore, as it seems the commit is lost somehow?

Could you kindly have a look? @acoulton @rjd22 @shadowhand

**Comment by enov** [comment]
Hmmm

image

image

**Comment by acoulton** [comment]
@enov it looks like maybe you force pushed to 3.3/develop shortly after, and simultaneously committed a direct merge from your feature branch to 3.4/develop in a222dd5 ?

image

The original PR merge commit is e2aaa90 which if you click in you'll see is no longer on any branch, because your subsequent push to 3.3/develop rewound the branch to 577de4b (the parent of 2e1e7d7 that you introduced in this PR).

2e1e7d7 is merged to 3.4/develop in a222dd5 which looks like you created it manually at your end.

Just looking at the best way to fix this.

**Comment by enov** [comment]
I did a direct merge from feature branch to `3.4/develop` because #55 clean up was needed for my test to run locally. Somehow [PHPUnit version reported by `PHPUnit_Runner_Version::id()`](https://github.com/kohana/unittest/blob/3.3/master/classes/Kohana/Unittest/TestCase.php#L49) was wrong similar to the case here https://travis-ci.org/kohana/core/jobs/83090586 . So basically that's why I did both #55 and #56.

I am sure I did not force push explicitly to those develop branches. But judging from the fact that both forced pushes have the same date/time, I might have performed a naked forced git push, with global git config to push on all branches.

I read that Github has [protected branches](https://github.com/blog/2051-protected-branches-and-required-status-checks). @shadowhand can you kindly protect the master and develop branches from forced pushes?

**Comment by acoulton** [comment]
@enov if you still have e2aaa90 in your local clone then this might work:

```
# Create temp branch with the lost merge commit - will fail if it's been garbage collected
git branch 3.3/develop-before-force-push e2aaa90

# Ensure that your local 3.3/develop is exactly in sync with github
git fetch origin
git branch -D 3.3/develop
git checkout 3.3/develop

# Merge the lost merge commit back into 3.3/develop
git merge 3.3/develop-before-force-push
git push origin 3.3/develop

# Merge the fixed 3.3/develop back into 3.4/develop
git branch -D 3.4/develop
git checkout 3.4/develop
git merge 3.3/develop
git push origin 3.4/develop
```

There's no way to fetch e2aaa90 from github because it's not referenced by any branch, so I can't do this from here for real.

I've just tried it by creating a fake version of e2aaa90 (an identical merge commit with a different SHA which ended up as 5c11cdd) and it worked as expected - the commits all end up in the right place with slightly odd history:

3.3/develop:
image

3.4/develop:
image

**Comment by acoulton** [comment]
@enov that makes sense and yes, was just about to suggest that @shadowhand set the protected branch flag for the various develop/master branches.

Also just occurred that the only bit of that fix you need to do locally is to create the 3.3/develop-before-force-push branch from e2aaa90, then you could do a normal push to github and do the merge to 3.3/develop and 3.3/develop => 3.4/develop in pull requests as normal.

If you don't have e2aaa90 then I think it might be possible to do it with the github API. From https://developer.github.com/v3/git/refs/#create-a-reference it looks like a POST to repos/kohana/unittest/git/refs with the following JSON might work:

```
{
  "ref": "refs/heads/3.3/develop-before-force-push",
  "sha": "e2aaa90a585a37419578c0de6fe76ccbc69eca9a"
}
```

**Comment by enov** [comment]
It seems it is garbage collected: `fatal: Not a valid object name: 'e2aaa90'.`

**Comment by acoulton** [comment]
@enov even better, I just hacked the github web interface to create the branch :)

I went to the kohana/unittest homepage and started as though I was going to create a new branch by typing a name in the branch dropdown. Then inspect the element and there's a hidden form field called `branch` which held the branch I was currently viewing. Change the value of that to the SHA of the commit to recover and submit and it worked. Clearly although that param is called branch under the hood they're able to spot an SHA and pass it through to the create-a-reference API.

image

See #57 for the merge from the lost commit back to 3.3/develop.

**Comment by enov** [comment]
@acoulton Excellent! You're awesome! :+1:

**Comment by acoulton** [comment]
@enov that was actually quite fun, it's nice finding undocumented features and I have no doubt it'll dig me out of a hole of my own one day :grinning:

**Comment by enov** [comment]
> undocumented features

Haha!

**Comment by enov** [comment]
I received the following instructions from John Greet (Github Staff):

> An interesting note on the undocumented feature mentioned here:
> 
> https://github.com/kohana/unittest/pull/55#issuecomment-145008222
> 
> Assuming you have write access to the repo, you can construct the URL for the tree view of the >unreferenced commit. For example:
> 
> https://github.com/kohana/unittest/tree/e2aaa90
> 
> And then use the branch drop down to create a new ref and fetch the commit. No Developer Tools trickery required.
> 
> Cheers,
> John

Thank you John.

**Comment by acoulton** [comment]
Ah that's handy. I had a go at doing it from the commit page but it never occurred to look at the tree. You learn something every day. Thank you John and @enov

**Pull request merged**
