### PR TITLE
3.2/develop

### PR DESCRIPTION
**Pull request by davidwinter**
Added support for PHPUnit 3.6+:

http://dev.kohanaframework.org/issues/4323

### CODE REVIEW

**Comment by drgomesp** [comment]
This actually doesn't solve the issue. 

PHPUnit 3.6 also returns TRUE from function_exists('phpunit_autoload').

What it needs to be done is PHPUnit_Runner_Version::id() to return the actual packave version.

I will fork this and fix it.

**Comment by drgomesp** [comment]
It's actually fixed in the newest version. Sorry for the mix up.

There is some:

session_start(): Cannot send session cookie - headers already sent by (output started at /usr/local/zend/apache2/htdocs/weingartner/modules/unittest/bootstrap.php:110) in /usr/local/zend/apache2/htdocs/weingartner/system/classes/kohana/session/native.php on line 43

Did you solve that?

**Comment by leth** [comment]
@drgomesp: #15 fixes that

**Comment by drgomesp** [comment]
In what branch that change is? beta/develop?

**Comment by leth** [comment]
It fixes the headers sent problem, and it's against 3.2/develop.

**Comment by acoulton** [comment]
I've created an alternative solution that works for PHPUnit 3.5 and 3.6 and allows the white and blacklisting to work properly - see https://github.com/kohana/unittest/pull/19

**Comment by drgomesp** [comment]
Good call @acoulton!

Ill fork this right away!

**Pull request closed without merging**
