### PR TITLE
Update PHPUnit it fix bootstrapping issue

### PR DESCRIPTION
**Pull request by rjd22**
@enov can you check this fix?

### CODE REVIEW

**Comment by enov** [comment]
:+1:

**Comment by rjd22** [comment]
@enov I can merge this right?

**Comment by enov** [comment]
Let's wait to see what @acoulton has to say with the way the tests are done
for PSR support.

**Comment by acoulton** [comment]
Merged - I think it's anyway good to reduce the range of PHPUnit versions we're supporting, given this will be a major release.

**Pull request merged**
