### PR TITLE
Use a more accurate version constraint for phpunit

### PR DESCRIPTION
**Pull request by shadowhand**
Any version better than 3.7 should work.

If the user needs a specific version, they can choose to limit it in their project composer.

### CODE REVIEW

**Comment by shadowhand** [comment]
@enov recreated #46.

**Comment by enov** [comment]
`^3.7` is equivalent to `>=3.7.0 <4.0.0`.

This won't affect the version downloaded, as PHPUnit `v3.7.38` is the latest of v3.

I would suggest `^4.0.0`. Also, such a change should be made on all modules, as well as the standard application `kohana/kohana` repository.

However, I am still not 100% sure that this should be made for Kohana v.3.3.

**Comment by acoulton** [comment]
What are the actual earliest and latest versions of phpunit we support? We should have the loosest possible constraint to match that, so end-users can specify a version to suit them. I think the other kohana repos all just depend on kohana/unittest so there shouldn't be a need to change anything there.

**Comment by acoulton** [comment]
In #45 @enov says our tests can run `using PHPUnit v3.7+ all the way up to v4.8+` - if that's right then shouldn't the constraint be `^3.7||^4`?

**Comment by shadowhand** [comment]
Or perhaps ~~`>=3.7,<=5.0`?~~ `3.7-4.0`.

**Comment by enov** [comment]
@shadowhand @acoulton 

Well, thinking more about this, I don't mind if we loosen the PHPUnit version constraint for Kohana v3.3. I see now that the other repos depend on this - except `kohana/kohana` has it. 

However, we should not loosen the PHPUnit version in future Kohana releases. Can't see a good way of running the tests on all applicable PHPUnit versions. Also, this module should be as thin as possible. In a perfect world, it should not even exist.

So, for Kohana v3.4... my suggestion is to drop PHPUnit 3.7 and stick with PHPUnit 4.0+ or even 4.2+ [because of HHVM's tests for the frameworks](https://github.com/facebook/hhvm/blob/master/hphp/test/frameworks/composer.json#L3)). The tighter and newer the versioning, the better, as we can leverage the new features, if any. We can still extend and add methods for DRY-ness, but we can at least drop the ones that were meant for cross PHPUnit support.

We can't support PHPUnit 5, as it does not support PHP 5.3, PHP 5.4, and PHP 5.5.

What do you say?

**Comment by shadowhand** [comment]
@enov this is [how you test with minimum and maximum versions](https://github.com/shadowhand/destrukt/blob/9ed99a6907bd006406af847208a9dc05dc686379/.travis.yml#L14-L17). What this will do is run the 5.4 test twice, once with lowest possible versions of packages, and one with highest. This _should_ cover 3.x and 4.x usage to make sure that nothing breaks.

Agree on switching to 4.x for v3.4+.

**Comment by shadowhand** [comment]
I've updated my PR to include Travis changes that expose testing lowest functionality.

**Comment by acoulton** [comment]
Sounds good, though I'm not sure why you're pinning the upper end of the range at `4.0` - won't that prevent using 4.1 etc? I think if you want to use a hyphen range it should be `3.7 - 4` to allow any 4.x.x version, or the `^3.7||^4` I suggested?

**Comment by shadowhand** [comment]
@acoulton no if you look at the [semver test](http://semver.mwl.be/#?package=phpunit%2Fphpunit&version=3.7%20-%204.0&minimum-stability=stable) it is effectively like `^3.7 - ~4.0` and includes all `4.x` versions.

**Comment by shadowhand** [comment]
The combination of `--prefer-dist` and `--prefer-stable` didn't make sense, hence the build failure. Fixed and rebuilding. :)

**Comment by acoulton** [comment]
@shadowhand interesting, then I think the docs are wrong at https://getcomposer.org/doc/articles/versions.md#range-hyphen- 

> Partial versions on the right include are completed with a wildcard. For example 1.0 - 2.0 is equivalent to >=1.0.0 <2.1 as the 2.0 becomes 2.0.*

Or am I missing something?

**Comment by shadowhand** [comment]
The docs _should_ say

> For example 1.0 - 2.0 is equivalent to >=1.0.0 <3.0 as the 2.0 becomes 2.*

At least according to the semver test that I linked and what we see in the travis builds.

On a separate issue, I have absolutely no idea why the Travis builds are failing. It seems like the installed composer might be ancient?

**Comment by acoulton** [comment]
I'll raise the versioning docs issue with composer.

The travis composer version is a bit old (2015-02-11) but I get the same issue on a current version locally. It seems `--prefer-lowest` is only a valid option for `composer update`, not `composer install`.

Since we don't use a lockfile, I guess we could use `composer update`?

**Comment by enov** [comment]
I've been playing on this right now, [here](https://github.com/kohana/unittest/compare/3.3/develop...3.3/hotfix/phpunit-version-with-sudo-false?expand=1) on a separate branch, and yeah it seems `--prefer-lowest` is only valid for `composer update`. But got [stuck again elsewhere](https://travis-ci.org/kohana/unittest/builds/79445373).

I using [this blog post](http://evertpot.com/testing-composer-prefer-lowest/) as a reference.

**Comment by enov** [comment]
I think, since we're "preferring lowest", then we're having also an older version of koharness.

**Comment by enov** [comment]
Hmmm... I have this working finally... Not so optimal, I used `composer require` instead of `composer update --prefer-lowest` to affect only PHPUnit version. However, I have set the lowest version of PHPUnit manually... If there's a way we could read it properly from `composer.json`, it would be great.

**Comment by acoulton** [comment]
What about `composer update --prefer-lowest --with-dependencies phpunit/phpunit` would that work? Sorry, not at a machine or I'd try

**Comment by enov** [comment]
Also note that, regarding the notation `3.7 - 4.0`: it is loading PHPUnit 4.0.20 as the highest version. So it seems there might be something wrong on the [semver test](http://semver.mwl.be/#?package=phpunit%2Fphpunit&version=3.7%20-%204.0&minimum-stability=stable)...

Here's again [the branch I worked on](https://github.com/kohana/unittest/compare/3.3/develop...3.3/hotfix/phpunit-version-with-sudo-false?expand=1).

**Comment by enov** [comment]
@acoulton Hmmm, no idea, would that affect only PHPUnit? I'd test.

**Comment by enov** [comment]
Whoaaaa, [that indeed worked!](https://github.com/kohana/unittest/compare/3.3/develop...3.3/hotfix/phpunit-version-prefer-lowest?expand=1) I had to fix the lowest PHPUnit version... and the command `composer update --prefer-lowest --with-dependencies phpunit/phpunit` only affected PHPUnit version! Thanks @acoulton! Congrats!

**Comment by acoulton** [comment]
@shadowhand seems composer's treatment of ranges has changed since the old version that ran https://travis-ci.org/kohana/unittest/jobs/79175469 on 8e9a247. I have just verified locally that with a range of `3.7 - 4.0` the old version (composer/composer@1d8f05f1dd0e390) installs `4.8.6` but the new version installs `4.0.20` per the docs. I think it's the semver test that is wrong.

@enov I just checked, that `composer update` on an empty checkout also installs all the other packages. So we should use an if/else in the travis.yml to run either `composer install` **or** `composer update` rather than slow the build by downloading then removing the newer versions.

Both of you - note that doing this in kohana/unittest is only going to cover the tests for this module and kohana/core, none of the other modules are installed for this build. So other modules could have tests that break on 3.7 and we'd never notice....

**Comment by acoulton** [comment]
Yep, the issue is the semver checker - they (and travis, by default) were using versions of composer that predate composer/composer#4096 which fixed a bug where `4.0` and `4` both (incorrectly) became `4.*`. Have filed an issue for them to update their composer version.

**Comment by enov** [comment]
@acoulton sorry for the late reply. I see that the semver checker is fixed now, and I suggest [`3.7.24-4`](http://semver.mwl.be/#?package=phpunit%2Fphpunit&version=3.7.24%20-%204&minimum-stability=stable). Yeah, an `if/else` to run either `composer install` or `composer update` might save us some 15s.

Speaking of seconds saved, a `sudo: false` at the start of `.travis.yml` makes use of [Travis' container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/) and builds start faster. Also, PHPUnit 4.8 felt slower than 4.0 by some 10s.

> Both of you - note that doing this in kohana/unittest is only going to cover the tests for this module and kohana/core, none of the other modules are installed for this build. So other modules could have tests that break on 3.7 and we'd never notice....

`.travis.yml` changes on all the modules and would solve the problem, no?

**Comment by shadowhand** [comment]
It's up to you two how you want to proceed with this, I think it would be be an improvement if:
- there was an extra test run with `--prefer-lowest` for every module
- package versions allowed newest stable versions whenever possible

**Comment by enov** [comment]
Thanks @shadowhand for the feedback.

@acoulton [I have tried](https://github.com/kohana/unittest/compare/3.3/develop...3.3/test/phpunit-version-lowest) your suggestion to run a single composer command, but without an `if/else` fork:

```
travis_retry composer update --no-interaction --prefer-dist ${COMPOSER_PHPUNIT_LOWEST}
```

with `COMPOSER_PHPUNIT_LOWEST` like this:

```
COMPOSER_PHPUNIT_LOWEST="--prefer-lowest --with-dependencies phpunit/phpunit"
```

It seems that when `composer update` is run for the first time, `--prefer-lowest` affects other packages as well, even when `phpunit/phpunit` argument is specified. A second composer command might be needed even if it slows up the build.

**Comment by enov** [comment]
Thanks @shadowhand for this original PR.

It was a good discussion and I have learned a lot from both of you.

This was done in #48 as well as in different related PRs in the other modules.

**Comment by enov** [comment]
By the way, I was thinking of adding `sudo: false` at the beginning of all `.travis.yml` files on all repos. It will make Travis builds to start up faster. Here are some links:
- [Blog: Faster Builds with Container-Based Infrastructure and Docker](http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/)
- [Docs: Migrating from legacy to container-based infrastructure](http://docs.travis-ci.com/user/migrating-from-legacy/)
- [Docs: Using container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/)

Kindly let me know if you want me to proceed with this.

Cheers!

**Comment by acoulton** [comment]
Thanks @enov that sounds like a good plan

**Pull request closed without merging**
